//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YWPatient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.diagnosis = new HashSet<diagnosi>();
        }
    
        public int categoryId { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<diagnosi> diagnosis { get; set; }
    }
}
