//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YWPatient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medication
    {
        public medication()
        {
            this.patientMedications = new HashSet<patientMedication>();
            this.treatments = new HashSet<treatment>();
        }
    
        public string din { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public int medicationTypeId { get; set; }
        public string dispensingCode { get; set; }
        public double concentration { get; set; }
        public string concentrationCode { get; set; }
    
        public virtual concentrationUnit concentrationUnit { get; set; }
        public virtual dispensingUnit dispensingUnit { get; set; }
        public virtual medicationType medicationType { get; set; }
        public virtual ICollection<patientMedication> patientMedications { get; set; }
        public virtual ICollection<treatment> treatments { get; set; }
    }
}
