//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YWPatient.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PatientSQLContext : DbContext
    {
        public PatientSQLContext()
            : base("name=PatientSQLContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<concentrationUnit> concentrationUnits { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<diagnosi> diagnosis { get; set; }
        public virtual DbSet<dispensingUnit> dispensingUnits { get; set; }
        public virtual DbSet<medication> medications { get; set; }
        public virtual DbSet<medicationType> medicationTypes { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<patientMedication> patientMedications { get; set; }
        public virtual DbSet<patientTreatment> patientTreatments { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<treatment> treatments { get; set; }
    }
}
