//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YWPatient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patientTreatment
    {
        public patientTreatment()
        {
            this.patientMedications = new HashSet<patientMedication>();
        }
    
        public int patientTreatmentId { get; set; }
        public Nullable<int> patientId { get; set; }
        public Nullable<int> treatmentId { get; set; }
        public System.DateTime datePrescribed { get; set; }
        public string comments { get; set; }
    
        public virtual patient patient { get; set; }
        public virtual ICollection<patientMedication> patientMedications { get; set; }
        public virtual treatment treatment { get; set; }
    }
}
