//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YWPatient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public patient()
        {
            this.patientTreatments = new HashSet<patientTreatment>();
        }
    
        public int patientId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string provinceCode { get; set; }
        public string postalCode { get; set; }
        public string OHIP { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public bool deceased { get; set; }
        public Nullable<System.DateTime> dateOfDeath { get; set; }
        public string homePhone { get; set; }
        public string gender { get; set; }
    
        public virtual province province { get; set; }
        public virtual ICollection<patientTreatment> patientTreatments { get; set; }
    }
}
