//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YWPatient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatment
    {
        public treatment()
        {
            this.patientTreatments = new HashSet<patientTreatment>();
            this.medications = new HashSet<medication>();
        }
    
        public int treatmentId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> diagnosisId { get; set; }
    
        public virtual diagnosi diagnosi { get; set; }
        public virtual ICollection<patientTreatment> patientTreatments { get; set; }
        public virtual ICollection<medication> medications { get; set; }
    }
}
